import type {
  UniverseNode,
  UniverseLink,
} from '../interfaces/universe-map.interface';

export const MATRIX_UNIVERSE_NODES: UniverseNode[] = [
  {
    id: 'Svar',
    name: 'Svar',
    color: '#00bfff',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335754/matrix/universe/svar.webp',
    alliance: 'Glacijská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Bhuuvar',
    name: 'Bhuvar',
    color: '#00bfff',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335734/matrix/universe/bhuvar.webp',
    alliance: 'Glacijská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Bhur',
    name: 'Bhúr',
    color: '#ffee00',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335733/matrix/universe/bhur.webp',
    alliance: 'Asgardská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Eden',
    name: 'Eden',
    color: '#ffee00',
    size: 6,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335735/matrix/universe/eden.webp',
    alliance: 'Asgardská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'MaanAshwada',
    name: "Ma'an Ashwada",
    color: '#ffee00',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335742/matrix/universe/maan_alfawda.webp',
    alliance: 'Asgardská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Yume',
    name: 'Yume',
    color: '#b24bf3',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335761/matrix/universe/yume.webp',
    alliance: 'Alfská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Asgard',
    name: 'Asgard',
    color: '#ffee00',
    size: 6,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335731/matrix/universe/asgard.webp',
    alliance: 'Asgardská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'AleasrAlthalith',
    name: 'Aleasr althalith',
    color: '#00bfff',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335729/matrix/universe/alqas_althalith.webp',
    alliance: 'Glacijská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Muspelheim',
    name: 'Muspelheim',
    color: '#222222',
    size: 6,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335746/matrix/universe/muspelheim.webp',
    alliance: 'Svobodná',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Alfheim',
    name: 'Alfheim',
    color: '#b24bf3',
    size: 6,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335728/matrix/universe/alfheim.webp',
    alliance: 'Alfská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Vanaheim',
    name: 'Vanaheim',
    color: '#11bb55',
    size: 6,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335759/matrix/universe/vanaheim.webp',
    alliance: 'Vanirská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Qiunxun',
    name: 'Qiunxun',
    color: '#11bb55',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335752/matrix/universe/qiunxun.webp',
    alliance: 'Vanirská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Folkvangr',
    name: 'Folkvangr',
    color: '#11bb55',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335736/matrix/universe/folkvangr.webp',
    alliance: 'Vanirská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Purgatorium',
    name: 'Purgatorium',
    color: '#11bb55',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335751/matrix/universe/purgatorium.webp',
    alliance: 'Vanirská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'AlsiniAlththani',
    name: 'Alsini alththani',
    color: '#00bfff',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335729/matrix/universe/alsini_alththani.webp',
    alliance: 'Glacijská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Simheim',
    name: 'Simheim',
    color: '#00bfff',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335753/matrix/universe/simheim.webp',
    alliance: 'Svobodná',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Midgard',
    name: 'Midgard',
    color: '#ffffff',
    size: 8,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335742/matrix/universe/midgard.webp',
    alliance: 'Lidská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Noutun',
    name: 'Noutun',
    color: '#11bb55',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335750/matrix/universe/noutun.webp',
    alliance: 'Vanirská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'AlsinuAlAwal',
    name: "Alsinu al'awal",
    color: '#00bfff',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335730/matrix/universe/alsinu_al_awal.webp',
    alliance: 'Glacijská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Jotunheim',
    name: 'Jotunheim',
    color: '#00bfff',
    size: 6,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335740/matrix/universe/jotunheim.webp',
    alliance: 'Glacijská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Svartalfheim',
    name: 'Svartalfheim',
    color: '#aa0000',
    size: 6,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335755/matrix/universe/svartalfheim.webp',
    alliance: 'Trpasličí',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Niflheim',
    name: 'Niflheim',
    color: '#00bfff',
    size: 6,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335749/matrix/universe/niflheim.webp',
    alliance: 'Glacijská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Babylon',
    name: 'Babylon',
    color: '#00bfff',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335732/matrix/universe/babylon.webp',
    alliance: 'Glacijská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Troja',
    name: 'Trója',
    color: '#222222',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335758/matrix/universe/troja.webp',
    alliance: 'Svobodná',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Olymp',
    name: 'Olymp',
    color: '#aa0000',
    size: 6,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335750/matrix/universe/olymp.webp',
    alliance: 'Trpasličí',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Hellheim',
    name: 'Hellheim',
    color: '#ffee00',
    size: 6,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335738/matrix/universe/hellheim.webp',
    alliance: 'Asgardská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Hvelgelmir',
    name: 'Hvelgelmir',
    color: '#888888',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335738/matrix/universe/hvelgelmir.webp',
    alliance: 'Nordská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Urdarbrunnr',
    name: 'Urdarbrunnr',
    color: '#888888',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335758/matrix/universe/urdarbrunnr.webp',
    alliance: 'Nordská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'VeschonechyeLesa',
    name: 'Veschonechye Lesa',
    color: '#aa0000',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335760/matrix/universe/veschonechye_lesa.webp',
    alliance: 'Trpasličí',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Mimirunnr',
    name: 'Mímismundr',
    color: '#888888',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335743/matrix/universe/mimirunnr.webp',
    alliance: 'Nordská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Nav',
    name: 'Nav',
    color: '#888888',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335747/matrix/universe/nav.webp',
    alliance: 'Nordská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Lachesis',
    name: 'Lachesis',
    color: '#888888',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335741/matrix/universe/lachesis.webp',
    alliance: 'Nordská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Tim',
    name: 'Tim',
    color: '#888888',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335757/matrix/universe/tim.webp',
    alliance: 'Nordská',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'Tartaros',
    name: 'Tartaros',
    color: '#aa0000',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335756/matrix/universe/tartaros.webp',
    alliance: 'Trpasličí',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'NeoKosmos',
    name: 'Neo Kosmos',
    color: '#aa0000',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335748/matrix/universe/neo_kosmos.webp',
    alliance: 'Svobodná',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'FranangrskeVodopady',
    name: 'Fránangrské vodopády',
    color: '#888888',
    size: 5,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335737/matrix/universe/franangrske_vodopady.webp',
    alliance: 'Svobodná',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'MoonMidgard',
    name: 'Měsíc',
    color: '#888888',
    size: 2,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335744/matrix/universe/moon.webp',
    type: 'moon',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'MoonAsgard',
    name: 'Měsíc',
    color: '#888888',
    size: 2,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335745/matrix/universe/moon_asgard.webp',
    type: 'moon',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'MoonInfernun',
    name: 'Infernun',
    color: '#888888',
    size: 2,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335739/matrix/universe/infernun.webp',
    type: 'moon',
    isPublic: true,
    visibleToPlayerIds: [],
  },
  {
    id: 'MoonCaelum',
    name: 'Caelum',
    color: '#888888',
    size: 2,
    img: 'https://res.cloudinary.com/dzht9sebg/image/upload/v1781335734/matrix/universe/caelum.webp',
    type: 'moon',
    isPublic: true,
    visibleToPlayerIds: [],
  },
];

export const MATRIX_UNIVERSE_LINKS: UniverseLink[] = [
  { source: 'Svar', target: 'Bhuuvar', isOrbit: false },
  { source: 'Svar', target: 'AlsiniAlththani', isOrbit: false },
  { source: 'Bhuuvar', target: 'Bhur', isOrbit: false },
  { source: 'Bhuuvar', target: 'AleasrAlthalith', isOrbit: false },
  { source: 'Bhuuvar', target: 'AlsiniAlththani', isOrbit: false },
  { source: 'Bhur', target: 'Eden', isOrbit: false },
  { source: 'Bhur', target: 'AleasrAlthalith', isOrbit: false },
  { source: 'Eden', target: 'Asgard', isOrbit: false },
  { source: 'Eden', target: 'AleasrAlthalith', isOrbit: false },
  { source: 'Eden', target: 'Muspelheim', isOrbit: false },
  { source: 'Eden', target: 'Qiunxun', isOrbit: false },
  { source: 'MaanAshwada', target: 'Asgard', isOrbit: false },
  { source: 'Yume', target: 'Asgard', isOrbit: false },
  { source: 'Yume', target: 'Alfheim', isOrbit: false },
  { source: 'Asgard', target: 'Alfheim', isOrbit: false },
  { source: 'Asgard', target: 'Muspelheim', isOrbit: false },
  { source: 'Asgard', target: 'Vanaheim', isOrbit: false },
  { source: 'AleasrAlthalith', target: 'Muspelheim', isOrbit: false },
  { source: 'AleasrAlthalith', target: 'Simheim', isOrbit: false },
  { source: 'AleasrAlthalith', target: 'AlsiniAlththani', isOrbit: false },
  { source: 'Muspelheim', target: 'Alfheim', isOrbit: false },
  { source: 'Muspelheim', target: 'Simheim', isOrbit: false },
  { source: 'Muspelheim', target: 'Midgard', isOrbit: false },
  { source: 'Alfheim', target: 'Midgard', isOrbit: false },
  { source: 'Alfheim', target: 'Vanaheim', isOrbit: false },
  { source: 'Vanaheim', target: 'Midgard', isOrbit: false },
  { source: 'Vanaheim', target: 'Qiunxun', isOrbit: false },
  { source: 'Vanaheim', target: 'Noutun', isOrbit: false },
  { source: 'Vanaheim', target: 'Folkvangr', isOrbit: false },
  { source: 'Qiunxun', target: 'Folkvangr', isOrbit: false },
  { source: 'Qiunxun', target: 'Purgatorium', isOrbit: false },
  { source: 'Qiunxun', target: 'FranangrskeVodopady', isOrbit: false },
  { source: 'Folkvangr', target: 'Noutun', isOrbit: false },
  { source: 'Folkvangr', target: 'Purgatorium', isOrbit: false },
  { source: 'AlsiniAlththani', target: 'Simheim', isOrbit: false },
  { source: 'AlsiniAlththani', target: 'AlsinuAlAwal', isOrbit: false },
  { source: 'Simheim', target: 'Midgard', isOrbit: false },
  { source: 'Simheim', target: 'AlsinuAlAwal', isOrbit: false },
  { source: 'Simheim', target: 'Jotunheim', isOrbit: false },
  { source: 'Simheim', target: 'Svartalfheim', isOrbit: false },
  { source: 'Midgard', target: 'Jotunheim', isOrbit: false },
  { source: 'Midgard', target: 'Svartalfheim', isOrbit: false },
  { source: 'Midgard', target: 'Niflheim', isOrbit: false },
  { source: 'Midgard', target: 'Noutun', isOrbit: false },
  { source: 'Noutun', target: 'Niflheim', isOrbit: false },
  { source: 'AlsinuAlAwal', target: 'Jotunheim', isOrbit: false },
  { source: 'AlsinuAlAwal', target: 'Babylon', isOrbit: false },
  { source: 'Jotunheim', target: 'Babylon', isOrbit: false },
  { source: 'Jotunheim', target: 'Svartalfheim', isOrbit: false },
  { source: 'Jotunheim', target: 'Hellheim', isOrbit: false },
  { source: 'Svartalfheim', target: 'Hellheim', isOrbit: false },
  { source: 'Svartalfheim', target: 'Niflheim', isOrbit: false },
  { source: 'Niflheim', target: 'Hellheim', isOrbit: false },
  { source: 'Niflheim', target: 'Hvelgelmir', isOrbit: false },
  { source: 'Niflheim', target: 'Urdarbrunnr', isOrbit: false },
  { source: 'Babylon', target: 'VeschonechyeLesa', isOrbit: false },
  { source: 'Babylon', target: 'Troja', isOrbit: false },
  { source: 'Troja', target: 'VeschonechyeLesa', isOrbit: false },
  { source: 'Troja', target: 'Olymp', isOrbit: false },
  { source: 'VeschonechyeLesa', target: 'Olymp', isOrbit: false },
  { source: 'VeschonechyeLesa', target: 'Nav', isOrbit: false },
  { source: 'Olymp', target: 'Hellheim', isOrbit: false },
  { source: 'Olymp', target: 'Tartaros', isOrbit: false },
  { source: 'Olymp', target: 'Svartalfheim', isOrbit: false },
  { source: 'Tartaros', target: 'Hellheim', isOrbit: false },
  { source: 'Tartaros', target: 'Lachesis', isOrbit: false },
  { source: 'Tartaros', target: 'NeoKosmos', isOrbit: false },
  { source: 'MoonMidgard', target: 'Midgard', isOrbit: true },
  { source: 'MoonAsgard', target: 'Asgard', isOrbit: true },
  { source: 'MoonCaelum', target: 'Tartaros', isOrbit: true },
  { source: 'MoonInfernun', target: 'Purgatorium', isOrbit: true },
  { source: 'Mimirunnr', target: 'Nav', isOrbit: false },
  { source: 'Mimirunnr', target: 'Hvelgelmir', isOrbit: false },
  { source: 'Mimirunnr', target: 'Lachesis', isOrbit: false },
  { source: 'Mimirunnr', target: 'Urdarbrunnr', isOrbit: false },
  { source: 'Mimirunnr', target: 'Jotunheim', isOrbit: false },
  { source: 'Hvelgelmir', target: 'Urdarbrunnr', isOrbit: false },
  { source: 'Hvelgelmir', target: 'Tim', isOrbit: false },
  { source: 'Urdarbrunnr', target: 'Tim', isOrbit: false },
  { source: 'Nav', target: 'Lachesis', isOrbit: false },
  { source: 'Lachesis', target: 'NeoKosmos', isOrbit: false },
];
